# Neural Networks
## Tensor

In [1]:
import torch

def activation(x):
    """Sigmoid activation function.

    Arguments:
    ---------
    x: torch.Tensor
    """
    return 1 / (1 + torch.exp(-x))

In [2]:
### Generate some data.
torch.manual_seed(7)  # Set the random seed so things are predictable.

# Features are 5 random normal variables.
features = torch.randn((1, 5))
# True weights for our data, random normal variables again.
weights = torch.randn_like(features)
# and a true bias term.
bias = torch.randn((1, 1))


In [3]:
weights.shape

torch.Size([1, 5])

In [4]:
## Calculate the output of this network using the weights and bias tensors.
features.shape #torch.Size([1, 5])
weights.shape #torch.Size([1, 5])
weights = weights.view(5, 1)
torch.mm(features, weights)

tensor([[-1.9796]])

In [5]:
### Generate some data.
torch.manual_seed(7)  # Set the random seed so things are predictable.

# Features are 3 random normal variables.
features = torch.randn((1, 3))

# Define the size of each layer in our network.
n_input = features.shape[1]  # Number of input units, must match number of input features.
n_hidden = 2  # Number of hidden units.
n_output = 1  # Number of output units.

# Weights for inputs to hidden layer.
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer.
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers.
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [6]:
## Your solution here.
hidden_features = torch.mm(features, W1) + B1
torch.mm(hidden_features, W2) + B2

tensor([[-1.1200]])

In [7]:
features

tensor([[-0.1468,  0.7861,  0.9468]])

## Numpy to Torch and back

In [8]:
import numpy as np

np.set_printoptions(precision=8)
a = np.random.rand(4, 3)
a

array([[0.48309241, 0.29614967, 0.75411352],
       [0.69486168, 0.10217174, 0.73878238],
       [0.20514574, 0.74813115, 0.88972418],
       [0.1891552 , 0.3779942 , 0.10370971]])

In [9]:
torch.set_printoptions(precision=8)
b = torch.from_numpy(a)
b

tensor([[0.48309241, 0.29614967, 0.75411352],
        [0.69486168, 0.10217174, 0.73878238],
        [0.20514574, 0.74813115, 0.88972418],
        [0.18915520, 0.37799420, 0.10370971]], dtype=torch.float64)

In [10]:
# Multiply PyTorch Tensor by 2, in place.
b.mul_(2)

tensor([[0.96618482, 0.59229934, 1.50822704],
        [1.38972335, 0.20434349, 1.47756476],
        [0.41029147, 1.49626229, 1.77944836],
        [0.37831040, 0.75598840, 0.20741942]], dtype=torch.float64)

In [11]:
# Numpy array matches new values from Tensor.
a

array([[0.96618482, 0.59229934, 1.50822704],
       [1.38972335, 0.20434349, 1.47756476],
       [0.41029147, 1.49626229, 1.77944836],
       [0.3783104 , 0.7559884 , 0.20741942]])